import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// this is the main entry point of the app.
// anything written here will be displayed in every route page
// all pages are its children

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
